version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-image-verification
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=""
    restart: unless-stopped
