version: "3.9"

services:
  fastapi:
    build: .
    container_name: deep_face
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
      - ./src:/app/src
    environment:
      - DATABASE_DIR=/app/database
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000